### ISSUE TITLE
Parker convention

### ISSUE THREAD

**Issue by pratapvardhan** [sanand0/xmljson#1]
If my understanding is right, for parker convention

``` python
# xml structure as 
 <root><item>1</item><item>2</item><item>three</item></root>
# gives json
 {"item":["1","2","three"]} NOT ["1","2","three"]
```

right? (More [details](https://github.com/shamblett/xml2json/blob/master/lib/src/Xml2JsonParker.dart#L22))
However, in the current implementation

``` python
parker.data(fromstring('<root><item>1</item><item>2</item><item>three</item></root>'))
# gives
{'root': {'item': [{}, {}, {}]}}
```

Gives empty sets.

**Comment by sanand0** [comment]
Fixed by 902c42c and released as [0.1.1](https://pypi.python.org/pypi/xmljson/0.1.1)
