### ISSUE TITLE
Remove prefiexes

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [sanand0/xmljson#10]
I am aware that the default prefix is "@". but can we remove that?

**Comment by sanand0** [comment]
@Dean-Christian-Armada -- you may want to use the [Yahoo convention](https://developer.yahoo.com/javascript/json.html#xml) in that case.

``` python
>>> from xmljson import yahoo
>>> from xml.etree.ElementTree import fromstring
>>> from json import dumps
>>> dumps(yahoo.data(fromstring('<p id="main">Hello<b>bold</b></p>')))
'{"p": {"id": "main", "content": "Hello", "b": "bold"}}'
```

Is this what you needed?

**Comment by Dean-Christian-Armada** [comment]
THANKS!
