### ISSUE TITLE
Given JSON example does not convert to XML correctly

### ISSUE THREAD

**Issue by sidhire** [sanand0/xmljson#15]
The code runs as:
```
>>> temp = {'employees': [{'person': {'name': {'@value': 'Alice'}}}, {'person': {'name': {'@value': 'Bob'}}}]}

>>> tostring(bf.etree(temp, root=Element('root')))
'<root><employees><person><name value="Alice" /></person></employees><employees><person><name value="Bob" /></person></employees></root>'
```

While the example says it should convert to:
```
'<root><employees><person><name value="Alice" /></person><person><name value="Bob" /></person></employees></root>'
```

Converting this using `tostring(bf.etree...)` results in the correct XML:
```
{
  "employees": {
    "person": [
      {
        "name": {
          "@value": "Alice"
        }
      },
      {
        "name": {
          "@value": "Bob"
        }
      }
    ]
  }
}
```

**Comment by dagwieers** [comment]
Hmm, I cannot find this specific example you mention. The XML and JSON at the top of the README do seem to be correct !

**Comment by sanand0** [comment]
Yes - I am unable to find the incorrect example as well. @sidhire could you please point us to where you found the example result?

**Comment by dagwieers** [comment]
Let's close this issue. Please reopen and provide more information if this problem still exists.

**Comment by sanand0** [comment]
Agreed.
