### ISSUE TITLE
Have you looked at jxmlease?

### ISSUE THREAD

**Issue by rcooke** [sanand0/xmljson#25]
It was created for a book on automating Juniper 2 years ago.  Seems really sophisticated.  Just wondering if you happened to base your project on it - which would be a cool idea I think.

https://github.com/Juniper/jxmlease

**Comment by sanand0** [comment]
@rcooke - thanks, wasn't aware of jxmlease, and it does look interesting. It seems a more powerful way of converting XML to Python data structures than xmljson intends to be.

*This* project is focused on converting purely into JSON, not a Python data structure. The output, therefore, has no structure or methods beyond what a JSON object can offer. So in that sense, the intent is different.
