### ISSUE TITLE
Does this project need a maintainer?

### ISSUE THREAD

**Issue by imaia** [sanand0/xmljson#5]

**Comment by sanand0** [comment]
Having a maintainer always helps @imaia. Were you interested? Did you have any features / bugs in mind?

**Comment by imaia** [comment]
Yes I am and yes I do. I was thinking about how to make the parser more "large files" friendly and approaches to do that (like handling iter params, etc). The way things are, it seems parsing big xml files can still be improved.

**Comment by sanand0** [comment]
@imaia -- apologies for the late revert -- and clearly I do not have bandwidth to maintain this project.

Yes, I'd be glad for you to take it up, if you're still up to it. To begin with, perhaps you could send merge requests -- either for existing bugs or new features? After some activity and I pass on my understanding to you, will add you as an owner to this repo?
